title = "Baptiste Pesquet"
# disqusShortname = "bpesquet"
enableGitInfo = true
googleAnalytics = "UA-39897312-4"
staticDir = ["static/common"]
DefaultContentLanguage = "fr"

[params]
    profilePic = "images/profile.png"
    author = "Baptiste Pesquet"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["javascript", "bash", "csharp", "python", "php"]
    description = "Engineer | Teacher | Consultant"
    fields = "Computer Science & Artificial Intelligence"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "cv.pdf"
    name = "CV"
    weight = 2

[[menu.main]]
    url = "/article/"
    name = "Blog"
    weight = 3

[[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    weight = 4

[[menu.main]]
    url = "/course/"
    name = "Courses"
    parent = "teaching"
    weight = 1

[[menu.main]]
    url = "/slides/"
    name = "Slides"
    parent = "teaching"
    weight = 2

[[menu.main]]
    url = "/publication/"
    name = "Publications"
    parent = "teaching"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:bpesquet [at] gmail [dot] com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/bpesquet/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/bpesquet/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.medium.com/@bpesquet/"
    name = "medium"
    weight = 4

[[menu.icon]]
    url = "http://www.pearltrees.com/bpesquet"
    name = "bookmark"
    weight = 5

[[menu.icon]]
    url = "https://www.linkedin.com/in/bpesquet/"
    name = "linkedin"
    weight = 6

[related]
includeNewer = true   # Here our relationship is timeless! This prevents Hugo from ignoring newer posts.

[[related.indices]]
    name = "course"   # The name of the indice, same as Front Matter's .Param key.
    weight = 1        # We don't really need this, but omitting it would disable the indice.
